/**
 * secure_tokens.js - Obfuscated Credentials
 * Generated by OpenCode Auto-Refactor
 */
window.SECURE_TOKENS = {
    "dad": "MTQzNQ==",
    "mom": "ODUzNQ==",
    "sieun": "ODUzNA==",
    "harong": "NzY1Nw=="
};
console.log('[Security] Tokens loaded.');
