/**
 * conversation.js - Final Ultimate Edition Ver 7.0
 * Generated by Python Converter
 */

(function injectStyles() {
    const oldStyle = document.getElementById('conversation-styles');
    if (oldStyle) oldStyle.remove();
    const css = `
       .perspective-1000 { perspective: 1000px; }
       .transform-style-3d { transform-style: preserve-3d; }
       .backface-hidden { backface-visibility: hidden; -webkit-backface-visibility: hidden; }
       .rotate-y-180 { transform: rotateY(180deg); }
       .card-inner { transition: transform 0.6s cubic-bezier(0.4, 0.0, 0.2, 1); }
       .flip-card.flipped .flip-card-inner { transform: rotateY(180deg); }
       .sticky-nav-container {
            position: sticky; top: 0; z-index: 999;
            background: rgba(255, 255, 255, 0.96);
            backdrop-filter: blur(10px);
            border-bottom: 1px solid #e5e7eb;
            padding: 10px 0; margin-bottom: 20px; width: 100%;
            box-shadow: 0 4px 6px -1px rgba(0, 0, 0, 0.05);
        }
       .btn-auto-active {
            background-color: #ef4444!important; color: white!important; border-color: #ef4444!important;
            animation: pulse-red 2s infinite;
        }
        @keyframes pulse-red { 
            0% { box-shadow: 0 0 0 0 rgba(239, 68, 68, 0.7); }
            70% { box-shadow: 0 0 0 10px rgba(239, 68, 68, 0); }
            100% { box-shadow: 0 0 0 0 rgba(239, 68, 68, 0); }
        }
       .vocab-grid { display: flex; flex-wrap: wrap; gap: 8px; align-content: flex-start; }
       .vocab-item { flex: 1 1 auto; min-width: 110px; max-width: 100%; display: flex; flex-direction: column; justify-content: space-between; }
       .no-scrollbar::-webkit-scrollbar { display: none; }
       .custom-scrollbar::-webkit-scrollbar { width: 4px; }
       .custom-scrollbar::-webkit-scrollbar-track { background: transparent; }
       .custom-scrollbar::-webkit-scrollbar-thumb { background: #cbd5e1; border-radius: 10px; }
       .animate-fade-in { animation: fadeIn 0.4s ease-out forwards; }
        @keyframes fadeIn { from { opacity: 0; transform: translateY(10px); } to { opacity: 1; transform: translateY(0); } }
       .playing-highlight { border: 2px solid #3b82f6; background-color: #eff6ff; transform: scale(1.02); transition: all 0.3s; }
    `;
    const style = document.createElement('style');
    style.id = 'conversation-styles';
    style.textContent = css;
    document.head.appendChild(style);
})();
// Migrated to Backend API
let conversationModuleData = {};

async function loadConversationData() {
    try {
        const categories = await ApiClient.getConversationCategories();
        if (categories) {
            // Optimization: Let's fill the metadata first.
            conversationModuleData = categories;

            // Trigger render
            renderConversationCategories();
        }
    } catch (e) {
        console.error("Failed to load conversation data", e);
    }
}

// Override or hook into init
const originalInitConversation = window.initConversation || function () { };
window.initConversation = async function () {
    await loadConversationData();
    originalInitConversation(); // This might try to render, so we called render above too.
};

function loadConversationCategory(category) {
    currentConversationCategory = category;
    currentConversationIndex = 0;

    const categoryContainer = document.getElementById('conversation-categories');
    const listContainer = document.getElementById('conversation-list');

    if (categoryContainer) categoryContainer.classList.add('hidden');
    if (listContainer) listContainer.classList.remove('hidden');

    displayCurrentConversation();
}

function displayCurrentConversation() {
    const listContainer = document.getElementById('conversation-viewer');
    if (!listContainer) return;

    const convData = conversationModuleData[currentConversationCategory];
    const conv = convData.conversations[currentConversationIndex];

    // Update Navigation State
    updateNavigationButtons();

    // Render Card
    listContainer.innerHTML = createFlipCardHTML(conv, currentConversationIndex);

    // Auto-scroll to top
    window.scrollTo({ top: 0, behavior: 'smooth' });
}

// Restore missing functions
function backToCategories() {
    if (typeof AudioController !== 'undefined') AudioController.stopAutoRepeat();
    const listContainer = document.getElementById('conversation-list');
    const categoryContainer = document.getElementById('conversation-categories');
    if (listContainer) listContainer.classList.add('hidden');
    if (categoryContainer) categoryContainer.classList.remove('hidden');
}

// Alias for compatibility
const openConversationCategory = loadConversationCategory;

// 전역 노출
window.initConversation = initConversation;
window.initDayConversation = initDayConversation;
window.loadConversationCategory = loadConversationCategory;
window.openConversationCategory = openConversationCategory;
window.backToCategories = backToCategories;
window.togglePracticalDay = togglePracticalDay;
window.toggleCardFlip = toggleCardFlip;
window.AudioController = AudioController;

console.log('conversation.js loaded');
