const fs = require('fs');
const path = require('path');

const rootDir = path.join(__dirname, '..');
const sourceFile = path.join(rootDir, 'js/travel/fukuoka_poi_data.js');
const targetJson = path.join(rootDir, 'data/fukuoka_poi.json');
const consumerFile = path.join(rootDir, 'js/travel/fukuoka.js');

console.log('🚀 OpenCode: Starting Data Separation...');

// 1. Read Source File
let content = fs.readFileSync(sourceFile, 'utf8');

// 2. Extract Data using Regex (assuming it starts with window.FUKUOKA_POI_DATABASE = [ ... ];)
const match = content.match(/window\.FUKUOKA_POI_DATABASE\s*=\s*(\[[\s\S]*?\]);/);

if (match && match[1]) {
    try {
        // Evaluate the array string to get the JS object (handles comments/trailing commas loosely)
        // using Function constructor is safer than eval for local trusted code context
        const dataArr = new Function('return ' + match[1])();

        // 3. Write JSON
        fs.writeFileSync(targetJson, JSON.stringify(dataArr, null, 2));
        console.log(`✅ Extracted ${dataArr.length} items to ${targetJson}`);

        // 4. Update Source File to use Fetch
        const newSourceContent = `/**
 * 후쿠오카 여행 POI 데이터 (JSON Fetch 방식)
 * Auto-generated by OpenCode
 */
window.fukuokaDataPromise = fetch('data/fukuoka_poi.json')
    .then(response => response.json())
    .then(data => {
        window.FUKUOKA_POI_DATABASE = data;
        console.log('[Fukuoka POI] Loaded ' + data.length + ' items via Fetch.');
        return data;
    })
    .catch(err => console.error('[Fukuoka POI] Load Error:', err));
`;
        fs.writeFileSync(sourceFile, newSourceContent);
        console.log(`✅ Updated ${sourceFile} to fetch logic`);

        // 5. Update Consumer (fukuoka.js) to be Async
        let consumerContent = fs.readFileSync(consumerFile, 'utf8');

        // Replace init function definition
        if (!consumerContent.includes('async function')) {
            consumerContent = consumerContent.replace(
                'window.initFukuokaTrip = function () {',
                'window.initFukuokaTrip = async function () {'
            );

            // Add wait logic
            const injectionPoint = "console.log('[Fukuoka] Initializing trip...');";
            const waitLogic = `
    // Wait for Data Promise if not ready
    if (!window.FUKUOKA_POI_DATABASE) {
        console.log('[Fukuoka] Waiting for data...');
        await window.fukuokaDataPromise;
    }`;

            consumerContent = consumerContent.replace(injectionPoint, injectionPoint + waitLogic);

            fs.writeFileSync(consumerFile, consumerContent);
            console.log(`✅ Updated ${consumerFile} to handle async data`);
        } else {
            console.log(`ℹ️ ${consumerFile} already seems async.`);
        }

    } catch (e) {
        console.error('❌ Error parsing extracted data:', e);
    }
} else {
    console.error('❌ Could not find window.FUKUOKA_POI_DATABASE pattern.');
}
