const fs = require('fs');
const path = require('path');

const authPath = path.join(__dirname, '../js/auth.js');
const tokenPath = path.join(__dirname, '../js/secure_tokens.js');

// 1. Read auth.js
let authContent = fs.readFileSync(authPath, 'utf8');

// 2. Extract Credentials Block
// We look for: credentials: { ... }
const credRegex = /credentials:\s*({[\s\S]*?})/;
const match = authContent.match(credRegex);

if (match) {
    const credBlock = match[1];

    // Parse the block (a bit hacky but works for this specific file structure)
    // We expect lines like: key: 'value',
    const lines = credBlock.split('\n');
    const tokens = {};

    lines.forEach(line => {
        const lineMatch = line.match(/^\s*(\w+):\s*'(\d+)'/);
        if (lineMatch) {
            const user = lineMatch[1];
            const pass = lineMatch[2];
            // Simple Base64 obfuscation to "hide" them from plain sight
            tokens[user] = Buffer.from(pass).toString('base64');
        }
    });

    console.log('Extracted Tokens:', tokens);

    // 3. Create secure_tokens.js
    const tokenFileContent = `/**
 * secure_tokens.js - Obfuscated Credentials
 * Generated by OpenCode Auto-Refactor
 */
window.SECURE_TOKENS = ${JSON.stringify(tokens, null, 4)};
console.log('[Security] Tokens loaded.');
`;
    fs.writeFileSync(tokenPath, tokenFileContent, 'utf8');
    console.log(`✅ Created ${tokenPath}`);

    // 4. Update auth.js
    // Replace the credentials block with a reference
    const newCredBlock = `credentials: (function() {
        const tokens = window.SECURE_TOKENS || {};
        const decoded = {};
        for (const [k, v] of Object.entries(tokens)) {
            try {
                decoded[k] = atob(v);
            } catch(e) { decoded[k] = null; }
        }
        return decoded;
    })()`;

    // We replace the WHOLE authConfig object definition to be safe/cleaner if needed, 
    // but replacing just the inner block preserves comments best.

    // Let's replace the specific lines.
    const newAuthContent = authContent.replace(credRegex, newCredBlock);

    fs.writeFileSync(authPath, newAuthContent, 'utf8');
    console.log(`✅ Updated ${authPath}`);

} else {
    console.log('❌ Could not find credentials block in auth.js');
}
