/**
 * 후쿠오카 여행 POI 데이터 (JSON Fetch 방식)
 * Auto-generated by OpenCode
 */
window.fukuokaDataPromise = fetch('data/fukuoka_poi.json')
    .then(response => response.json())
    .then(data => {
        window.FUKUOKA_POI_DATABASE = data;
        console.log('[Fukuoka POI] Loaded ' + data.length + ' items via Fetch.');
        return data;
    })
    .catch(err => console.error('[Fukuoka POI] Load Error:', err));